# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'WalkWithHaesook' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SwiftLint'
  pod 'NMapsMap'
  pod 'Firebase/Firestore'
  pod 'FirebaseFirestoreSwift'
  pod 'Kingfisher'
  pod 'KakaoSDKCommon'
  pod 'KakaoSDKAuth'
  pod 'KakaoSDKUser'

  # Pods for WalkWithHaesook

end
